### ISSUE TITLE
How to resume training? is it possible?

### ISSUE THREAD

**Issue by Kitty-sunray** [lubosmj/I2I-GANs#5]
Thanks for the info!

**Comment by lubosmj** [comment]
In the [examples](https://github.com/lubosmj/I2I-GANs/tree/main/examples), the [`ModelCheckpoint`](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint) callback is used for saving models' states. According to the docs, the saved states can be later loaded to continue the training (either by calling [load_model](https://www.tensorflow.org/api_docs/python/tf/keras/models/load_model) or [load_weights](https://www.tensorflow.org/api_docs/python/tf/keras/Model#load_weights)). The examples in this repository only demonstrate a way how the library may be used. You can find more details about saving and loading a model state at https://www.tensorflow.org/tutorials/keras/save_and_load.

Note that when you are trying to load a model in order to resume the training, do not forget to load the optimizer state as well. I would personally recommend you to take a look at https://www.tensorflow.org/guide/checkpoint.
